-- ============================================
-- File: 002_income_entries.sql
-- Purpose: Income entries table schema definition
-- Author: Copilot AI Assistant
-- Date: 2026-03-13
-- Version: 1.0 (DRAFT - Not yet implemented)
-- Dependencies: dbo schema
-- ============================================

-- Description:
-- This table will store monthly income entries for personal finance tracking.
-- Currently using localStorage in Angular app - will migrate to this table.
-- Includes unique constraint on (month, year) to prevent duplicates.

-- Status: ⏳ PENDING - To be implemented after localStorage testing complete


-- ============================================
-- 1) CREATE TABLE
-- ============================================

CREATE TABLE IF NOT EXISTS dbo.income_entries (
    -- Primary Key: Auto-incrementing integer
    income_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Month: Full name (e.g., "January", "February")
    month          VARCHAR(20) NOT NULL,
    
    -- Year: 4-digit year
    year           INTEGER NOT NULL,
    
    -- Amount: Income amount in INR (₹)
    -- Using DECIMAL for precise currency calculations
    amount         DECIMAL(12, 2) NOT NULL CHECK (amount >= 0),
    
    -- Source: Where income came from
    source         VARCHAR(100) NOT NULL DEFAULT 'Salary',
    
    -- Notes: Optional description/comments
    notes          TEXT,
    
    -- Date: ISO format date for sorting
    date           TIMESTAMPTZ NOT NULL,
    
    -- Audit Timestamps: Automatically managed
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    -- Unique constraint: Prevent duplicate entries for same month/year
    CONSTRAINT ux_income_month_year UNIQUE (month, year)
);


-- ============================================
-- 2) CREATE INDEXES
-- ============================================

-- Index for year-based queries (most common filter)
CREATE INDEX IF NOT EXISTS idx_income_year 
  ON dbo.income_entries(year DESC);

-- Index for date-based sorting
CREATE INDEX IF NOT EXISTS idx_income_date 
  ON dbo.income_entries(date DESC);

-- Index for source-based filtering
CREATE INDEX IF NOT EXISTS idx_income_source 
  ON dbo.income_entries(source);


-- ============================================
-- 3) CREATE TRIGGER FUNCTION (Auto-update timestamp)
-- ============================================

CREATE OR REPLACE FUNCTION dbo.set_income_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ============================================
-- 4) CREATE TRIGGER
-- ============================================

DROP TRIGGER IF EXISTS trg_income_updated_at ON dbo.income_entries;

CREATE TRIGGER trg_income_updated_at
BEFORE UPDATE ON dbo.income_entries
FOR EACH ROW
EXECUTE FUNCTION dbo.set_income_updated_at();


-- ============================================
-- VERIFICATION QUERIES
-- ============================================

-- Check table structure
-- SELECT column_name, data_type, is_nullable, column_default
-- FROM information_schema.columns 
-- WHERE table_schema = 'dbo' AND table_name = 'income_entries'
-- ORDER BY ordinal_position;

-- Check constraints
-- SELECT constraint_name, constraint_type
-- FROM information_schema.table_constraints
-- WHERE table_schema = 'dbo' AND table_name = 'income_entries';

-- Check indexes
-- SELECT indexname, indexdef 
-- FROM pg_indexes 
-- WHERE schemaname = 'dbo' AND tablename = 'income_entries';


-- ============================================
-- MIGRATION FROM LOCALSTORAGE
-- ============================================

-- When ready to migrate from localStorage to database:
-- 
-- 1. Export data from localStorage:
--    const data = JSON.parse(localStorage.getItem('cashflow_income_data'));
--    console.log(JSON.stringify(data, null, 2));
--
-- 2. Convert to INSERT statements:
--    INSERT INTO dbo.income_entries (month, year, amount, source, notes, date) VALUES
--    ('August', 2021, 45000, 'Salary', 'First month - Started earning', '2021-08-01T00:00:00Z'),
--    ('September', 2021, 45000, 'Salary', '', '2021-09-01T00:00:00Z'),
--    ...
--    ON CONFLICT (month, year) DO NOTHING;
--
-- 3. Update IncomeService to use Supabase instead of localStorage
-- 4. Test thoroughly before removing localStorage fallback


-- ============================================
-- ROLLBACK (How to undo)
-- ============================================

-- WARNING: This will delete all income data!
-- DROP TRIGGER IF EXISTS trg_income_updated_at ON dbo.income_entries;
-- DROP FUNCTION IF EXISTS dbo.set_income_updated_at();
-- DROP TABLE IF EXISTS dbo.income_entries CASCADE;


-- ============================================
-- NOTES
-- ============================================

-- 1. Month stored as full name for readability (not numeric)
-- 2. DECIMAL(12,2) allows amounts up to 9,999,999,999.99
-- 3. UNIQUE constraint on (month, year) prevents duplicate entries
-- 4. Check constraint ensures amount is never negative
-- 5. date column is TIMESTAMPTZ for proper timezone handling
-- 6. Trigger maintains updated_at automatically

-- Future enhancements to consider:
-- - Add user_id column for multi-user support
-- - Add currency column for multi-currency support
-- - Add category_id foreign key to link with expense categories
-- - Add payment_method column (bank transfer, cash, etc.)
-- - Add tags/labels for flexible categorization


-- ============================================
-- RELATED FILES
-- ============================================

-- Current Implementation: src/app/services/income.service.ts (localStorage)
-- Future Implementation: Will migrate to use this table
-- Migration Guide: docs/guides/SUPABASE_MIGRATION.md
-- Sample Data: src/app/data/income-data.json
