-- ============================================
-- File: 003_expense.sql
-- Purpose: Expense entries table schema definition
-- Author: Copilot AI Assistant
-- Date: 2026-03-22
-- Version: 1.0
-- Dependencies: dbo schema, category table
-- ============================================

-- Description:
-- This table stores expense entries for personal finance tracking.
-- Each expense is mapped to a category/subcategory from the category table.
-- Supports multiple entries per month (unlike income which is 1 per month).
-- Soft delete is implemented via is_delete flag.

-- Status: ⏳ PENDING - Using mock data in Angular until this table is created


-- ============================================
-- 1) CREATE TABLE
-- ============================================

CREATE TABLE IF NOT EXISTS dbo.expense (
    -- Primary Key: Auto-incrementing integer
    expense_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Date: When the expense occurred (YYYY-MM-DD)
    date              DATE NOT NULL,

    -- Month: Full name (e.g., "January", "February") — derived from date
    month             VARCHAR(20) NOT NULL,

    -- Year: 4-digit year — derived from date
    year              INTEGER NOT NULL,

    -- Category Reference (denormalized for performance)
    category_id       INTEGER NOT NULL,
    category_name     VARCHAR(50) NOT NULL,
    category_icon     VARCHAR(10),

    -- Subcategory (from category table's sub_category field)
    sub_category      VARCHAR(100),
    subcategory_icon  VARCHAR(10),

    -- Amount: Expense amount in INR (₹)
    amount_inr        DECIMAL(12, 2) NOT NULL CHECK (amount_inr >= 0),

    -- Notes: Optional description/comments
    notes             TEXT,

    -- Soft Delete Flag: FALSE = active, TRUE = deleted
    is_delete         BOOLEAN NOT NULL DEFAULT FALSE,

    -- Audit Timestamps: Automatically managed
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================
-- 2) CREATE INDEXES
-- ============================================

-- Index for filtering by year + month (most common query)
CREATE INDEX IF NOT EXISTS idx_expense_year_month
    ON dbo.expense (year, month);

-- Index for filtering by date range
CREATE INDEX IF NOT EXISTS idx_expense_date
    ON dbo.expense (date);

-- Index for category-based queries
CREATE INDEX IF NOT EXISTS idx_expense_category
    ON dbo.expense (category_name);

-- Index for soft-delete filter (most queries exclude deleted)
CREATE INDEX IF NOT EXISTS idx_expense_is_delete
    ON dbo.expense (is_delete);


-- ============================================
-- 3) CREATE TRIGGER FUNCTION (Auto-update timestamp)
-- ============================================

CREATE OR REPLACE FUNCTION dbo.set_expense_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ============================================
-- 4) CREATE TRIGGER
-- ============================================

DROP TRIGGER IF EXISTS trg_expense_updated_at ON dbo.expense;

CREATE TRIGGER trg_expense_updated_at
BEFORE UPDATE ON dbo.expense
FOR EACH ROW
EXECUTE FUNCTION dbo.set_expense_updated_at();


-- ============================================
-- 5) ENABLE ROW LEVEL SECURITY (Supabase)
-- ============================================

ALTER TABLE dbo.expense ENABLE ROW LEVEL SECURITY;

-- Allow all operations for authenticated users
CREATE POLICY "Enable all for authenticated users" ON dbo.expense
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Allow read for anonymous users (if needed)
CREATE POLICY "Enable read for anon" ON dbo.expense
    FOR SELECT
    TO anon
    USING (true);


-- ============================================
-- SAMPLE INSERT (for testing)
-- ============================================

-- INSERT INTO dbo.expense (date, month, year, category_id, category_name, category_icon, sub_category, subcategory_icon, amount_inr, notes)
-- VALUES 
--   ('2026-03-01', 'March', 2026, 1, 'Rent', '🏠', 'Monthly Rent', '🏡', 15000.00, 'March rent payment'),
--   ('2026-03-02', 'March', 2026, 2, 'Groceries', '🛒', 'Vegetables', '🥬', 2500.00, 'Weekly vegetables'),
--   ('2026-03-05', 'March', 2026, 3, 'Transport', '🚗', 'Fuel', '⛽', 3000.00, 'Petrol filling');


-- ============================================
-- VERIFICATION QUERIES
-- ============================================

-- Check table structure
-- SELECT * FROM information_schema.columns WHERE table_schema = 'dbo' AND table_name = 'expense';

-- Check indexes
-- SELECT * FROM pg_indexes WHERE schemaname = 'dbo' AND tablename = 'expense';

-- Total expenses for a month
-- SELECT SUM(amount_inr) as total FROM dbo.expense WHERE month = 'March' AND year = 2026 AND is_delete = false;

-- Category breakdown
-- SELECT category_name, category_icon, COUNT(*) as count, SUM(amount_inr) as total 
-- FROM dbo.expense WHERE month = 'March' AND year = 2026 AND is_delete = false
-- GROUP BY category_name, category_icon ORDER BY total DESC;


-- ============================================
-- ROLLBACK
-- ============================================

-- DROP TRIGGER IF EXISTS trg_expense_updated_at ON dbo.expense;
-- DROP FUNCTION IF EXISTS dbo.set_expense_updated_at();
-- DROP TABLE IF EXISTS dbo.expense CASCADE;


-- ============================================
-- NOTES
-- ============================================

-- 1. Unlike income (1 entry per month), expense allows multiple entries per month
-- 2. Category fields are denormalized — category_name, icon stored directly on expense
--    This avoids JOINs on every query and preserves historical category names
-- 3. Soft delete via is_delete — data never truly deleted for audit trail
-- 4. When USE_DB flag is set to true in expense.service.ts, Angular will use this table
-- 5. The trigger auto-updates updated_at on every UPDATE operation

-- ============================================
-- RELATED FILES
-- ============================================

-- Angular Service: src/app/services/expense.service.ts
-- Angular Component: src/app/component/expense/expense.page.ts
-- Category Table: sql/schemas/001_category.sql
-- Income Table: sql/schemas/002_income.sql
