-- ============================================
-- File: 005_tax.sql
-- Purpose: Tax entries table schema definition
-- Author: Copilot AI Assistant
-- Date: 2026-04-06
-- Version: 1.0
-- Dependencies: dbo schema
-- ============================================

-- Description:
-- This table stores monthly tax payment entries for personal finance tracking.
-- Each entry represents tax paid for a specific month in a calendar year.
-- Supports years 2021-2026 with up to 12 months per year.

-- ============================================
-- 1) CREATE TABLE
-- ============================================

CREATE TABLE IF NOT EXISTS dbo.tax_entries (
    -- Primary Key: Auto-incrementing integer
    tax_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Year: Calendar year (e.g., 2021, 2022, 2023, 2024, 2025, 2026)
    year           INTEGER NOT NULL CHECK (year BETWEEN 2021 AND 2030),
    
    -- Month: Month number (1-12)
    month          INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
    
    -- Tax Paid: Amount of tax paid in INR (₹)
    -- Using DECIMAL for precise currency calculations
    tax_paid       DECIMAL(12, 2) NOT NULL DEFAULT 0 CHECK (tax_paid >= 0),
    
    -- Taxable Income: Income for this month (optional)
    taxable_income DECIMAL(12, 2) DEFAULT 0 CHECK (taxable_income >= 0),
    
    -- Status: Payment status
    status         VARCHAR(20) NOT NULL DEFAULT 'paid' CHECK (status IN ('paid', 'pending', 'overdue')),
    
    -- Payment Date: When tax was paid
    payment_date   DATE,
    
    -- Payment Mode: How tax was paid
    payment_mode   VARCHAR(50) DEFAULT 'Online',
    
    -- Notes: Optional description/comments
    notes          TEXT,
    
    -- Audit Timestamps: Automatically managed
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_deleted     BOOLEAN NOT NULL DEFAULT FALSE,
    
    -- Unique constraint: Prevent duplicate entries for same month/year
    CONSTRAINT ux_tax_year_month UNIQUE (year, month)
);

-- ============================================
-- 2) CREATE INDEXES
-- ============================================

-- Index on year for fast year-based filtering
CREATE INDEX IF NOT EXISTS idx_tax_year ON dbo.tax_entries(year);

-- Index on month for monthly reports
CREATE INDEX IF NOT EXISTS idx_tax_month ON dbo.tax_entries(month);

-- Composite index on year and month for efficient queries
CREATE INDEX IF NOT EXISTS idx_tax_year_month ON dbo.tax_entries(year, month);

-- Index on status for filtering
CREATE INDEX IF NOT EXISTS idx_tax_status ON dbo.tax_entries(status);

-- Index on is_deleted for active records filtering
CREATE INDEX IF NOT EXISTS idx_tax_active ON dbo.tax_entries(is_deleted);

-- ============================================
-- 3) CREATE TRIGGER FOR UPDATED_AT
-- ============================================

CREATE OR REPLACE FUNCTION update_tax_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_tax_updated_at
BEFORE UPDATE ON dbo.tax_entries
FOR EACH ROW
EXECUTE FUNCTION update_tax_timestamp();

-- ============================================
-- 4) INSERT SAMPLE DATA (Optional)
-- ============================================

-- Sample data for 2025
INSERT INTO dbo.tax_entries (year, month, tax_paid, taxable_income, status, payment_date, notes) VALUES
(2025, 1, 15000.00, 100000.00, 'paid', '2025-02-10', 'January advance tax'),
(2025, 2, 15000.00, 100000.00, 'paid', '2025-03-10', 'February advance tax'),
(2025, 3, 15000.00, 100000.00, 'paid', '2025-04-10', 'March advance tax'),
(2025, 4, 15000.00, 100000.00, 'paid', '2025-05-10', 'Q1 advance tax'),
(2025, 5, 15000.00, 100000.00, 'paid', '2025-06-10', 'May advance tax'),
(2025, 6, 15000.00, 100000.00, 'paid', '2025-07-10', 'Q2 advance tax'),
(2025, 7, 15000.00, 100000.00, 'paid', '2025-08-10', 'July advance tax'),
(2025, 8, 15000.00, 100000.00, 'paid', '2025-09-10', 'August advance tax'),
(2025, 9, 15000.00, 100000.00, 'paid', '2025-10-10', 'Q3 advance tax'),
(2025, 10, 15000.00, 100000.00, 'pending', NULL, 'October tax due'),
(2025, 11, 0.00, 0.00, 'pending', NULL, 'November tax planned'),
(2025, 12, 0.00, 0.00, 'pending', NULL, 'Q4 advance tax planned')
ON CONFLICT (year, month) DO NOTHING;

-- Sample data for 2026
INSERT INTO dbo.tax_entries (year, month, tax_paid, taxable_income, status, payment_date, notes) VALUES
(2026, 1, 16000.00, 110000.00, 'paid', '2026-02-10', 'January advance tax'),
(2026, 2, 16000.00, 110000.00, 'paid', '2026-03-10', 'February advance tax'),
(2026, 3, 16000.00, 110000.00, 'paid', '2026-04-10', 'March advance tax'),
(2026, 4, 16000.00, 110000.00, 'pending', NULL, 'Q1 advance tax due')
ON CONFLICT (year, month) DO NOTHING;

-- ============================================
-- 5) COMMENTS
-- ============================================

COMMENT ON TABLE dbo.tax_entries IS 'Stores monthly tax payment entries for personal finance tracking';
COMMENT ON COLUMN dbo.tax_entries.tax_id IS 'Primary key - auto-incrementing';
COMMENT ON COLUMN dbo.tax_entries.year IS 'Calendar year (2021-2030)';
COMMENT ON COLUMN dbo.tax_entries.month IS 'Month number (1-12)';
COMMENT ON COLUMN dbo.tax_entries.tax_paid IS 'Amount of tax paid in INR';
COMMENT ON COLUMN dbo.tax_entries.taxable_income IS 'Taxable income for the month';
COMMENT ON COLUMN dbo.tax_entries.status IS 'Payment status: paid, pending, overdue';
COMMENT ON COLUMN dbo.tax_entries.payment_date IS 'Date when tax was paid';
COMMENT ON COLUMN dbo.tax_entries.payment_mode IS 'Payment method';
COMMENT ON COLUMN dbo.tax_entries.notes IS 'Additional notes or comments';
COMMENT ON COLUMN dbo.tax_entries.is_deleted IS 'Soft delete flag';

-- ============================================
-- END OF SCRIPT
-- ============================================
