-- public.category definition

-- Drop table

-- DROP TABLE public.category;

CREATE TABLE public.category (
	category_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	category_name varchar(50) NOT NULL,
	is_active bool NOT NULL DEFAULT true,
	created_at timestamptz NOT NULL DEFAULT now(),
	updated_at timestamptz NOT NULL DEFAULT now(),
	sub_category varchar(50) NULL,
	category_icon varchar(10) NULL,
	subcategory_icon varchar(10) NULL,
	notes text NULL,
	CONSTRAINT category_pkey PRIMARY KEY (category_id)
);
CREATE INDEX idx_category_name ON public.category USING btree (category_name);
CREATE INDEX idx_sub_category ON public.category USING btree (sub_category);
CREATE INDEX ix_category_subcategory ON public.category USING btree (sub_category) WHERE (sub_category IS NOT NULL);
CREATE UNIQUE INDEX ux_category_name_subcategory_ci ON public.category USING btree (lower((category_name)::text), lower((COALESCE(sub_category, ''::character varying))::text));

-- Table Triggers

create trigger trg_category_updated_at before
update
    on
    public.category for each row execute function dbo.set_category_updated_at();
	
---------------------------------------------	
	
	-- public.expense definition

-- Drop table

-- DROP TABLE public.expense;

CREATE TABLE public.expense (
	expense_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"month" varchar(20) NOT NULL,
	"year" int4 NOT NULL,
	category_id int4 NOT NULL,
	category_name varchar(50) NOT NULL,
	category_icon varchar(10) NULL,
	sub_category varchar(100) NULL,
	subcategory_icon varchar(10) NULL,
	amount_inr numeric(12, 2) NOT NULL,
	notes text NULL,
	is_delete bool NOT NULL DEFAULT false,
	created_at timestamptz NOT NULL DEFAULT now(),
	updated_at timestamptz NOT NULL DEFAULT now(),
	CONSTRAINT expense_amount_inr_check CHECK ((amount_inr >= (0)::numeric)),
	CONSTRAINT expense_pkey PRIMARY KEY (expense_id)
);
CREATE INDEX idx_expense_category ON public.expense USING btree (category_name);
CREATE INDEX idx_expense_is_delete ON public.expense USING btree (is_delete);
CREATE INDEX idx_expense_year_month ON public.expense USING btree (year, month);

-- Table Triggers

create trigger trg_expense_updated_at before
update
    on
    public.expense for each row execute function set_expense_updated_at();
	
	
-------------------------------------------
-- public.income definition

-- Drop table

-- DROP TABLE public.income;

CREATE TABLE public.income (
	income_id serial4 NOT NULL,
	"year" int4 NOT NULL,
	"month" varchar(20) NOT NULL,
	"date" date NULL,
	amount_inr numeric(15, 2) NOT NULL,
	"source" varchar(100) NULL DEFAULT 'Salary'::character varying,
	notes text NULL,
	is_delete bool NULL DEFAULT false,
	created_at timestamptz NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at timestamptz NULL DEFAULT CURRENT_TIMESTAMP,
	mnc_company varchar(100) NULL,
	CONSTRAINT chk_amount CHECK ((amount_inr >= (0)::numeric)),
	CONSTRAINT chk_month CHECK (((month)::text = ANY ((ARRAY['January'::character varying, 'February'::character varying, 'March'::character varying, 'April'::character varying, 'May'::character varying, 'June'::character varying, 'July'::character varying, 'August'::character varying, 'September'::character varying, 'October'::character varying, 'November'::character varying, 'December'::character varying])::text[]))),
	CONSTRAINT chk_year CHECK (((year >= 2000) AND (year <= 2100))),
	CONSTRAINT income_pkey PRIMARY KEY (income_id)
);
CREATE INDEX idx_income_created_at ON public.income USING btree (created_at);
CREATE INDEX idx_income_date ON public.income USING btree (date);
CREATE INDEX idx_income_is_delete ON public.income USING btree (is_delete);
CREATE INDEX idx_income_mnc_company ON public.income USING btree (mnc_company) WHERE (mnc_company IS NOT NULL);
CREATE INDEX idx_income_month ON public.income USING btree (month);
CREATE INDEX idx_income_year ON public.income USING btree (year);
CREATE UNIQUE INDEX unique_month_year ON public.income USING btree (year, month) WHERE (is_delete = false);

-- Table Triggers

create trigger update_income_updated_at before
update
    on
    public.income for each row execute function update_updated_at_column();
	
------------------------------------
CREATE OR REPLACE FUNCTION public.set_expense_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$function$
;


-----------------------------------------
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$function$
;

-----------------------------------------------