-- ============================================
-- File: 005_expense_yearly_tables_2021_2025.sql
-- Purpose: Create separate expense tables for years 2021-2025
-- Author: Copilot AI Assistant
-- Date: 2026-04-02
-- Version: 1.0
-- Dependencies: public schema, category table
-- ============================================

-- Description:
-- Due to Supabase free tier limitation of 1000 records per table,
-- we create separate expense tables for each year.
-- Current expense table holds 2026 data.
-- This script creates tables for: 2021, 2022, 2023, 2024, 2025

-- Status: ✅ READY - Execute this script in Supabase SQL Editor

-- ⚠️ IMPORTANT NOTES:
-- 1. Current 'expense' table will be renamed to 'expense_2026' later
-- 2. After creating tables, DISABLE RLS for each table
-- 3. Each table has same structure as original expense table


-- ============================================
-- EXPENSE TABLE 2021
-- ============================================

CREATE TABLE IF NOT EXISTS public.expense_2021 (
    -- Primary Key: Auto-incrementing integer
    expense_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Month: Full name (e.g., "January", "February")
    month             VARCHAR(20) NOT NULL,

    -- Year: 4-digit year (always 2021 for this table)
    year              INTEGER NOT NULL DEFAULT 2021,

    -- Category Reference (denormalized for performance)
    category_id       INTEGER NOT NULL,
    category_name     VARCHAR(50) NOT NULL,
    category_icon     VARCHAR(10),

    -- Subcategory (from category table's sub_category field)
    sub_category      VARCHAR(100),
    subcategory_icon  VARCHAR(10),

    -- Amount: Expense amount in INR (₹)
    amount_inr        DECIMAL(12, 2) NOT NULL CHECK (amount_inr >= 0),

    -- Notes: Optional description/comments
    notes             TEXT,

    -- Soft Delete Flag: FALSE = active, TRUE = deleted
    is_delete         BOOLEAN NOT NULL DEFAULT FALSE,

    -- Audit Timestamps: Automatically managed
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Constraint: Ensure year is 2021
    CONSTRAINT chk_expense_2021_year CHECK (year = 2021)
);

-- Indexes for expense_2021
CREATE INDEX IF NOT EXISTS idx_expense_2021_year_month ON public.expense_2021 (year, month);
CREATE INDEX IF NOT EXISTS idx_expense_2021_category ON public.expense_2021 (category_name);
CREATE INDEX IF NOT EXISTS idx_expense_2021_is_delete ON public.expense_2021 (is_delete);

-- Trigger for auto-update timestamp
DROP TRIGGER IF EXISTS trg_expense_2021_updated_at ON public.expense_2021;
CREATE TRIGGER trg_expense_2021_updated_at
    BEFORE UPDATE ON public.expense_2021
    FOR EACH ROW
    EXECUTE FUNCTION public.set_expense_updated_at();

-- Disable RLS
ALTER TABLE public.expense_2021 DISABLE ROW LEVEL SECURITY;


-- ============================================
-- EXPENSE TABLE 2022
-- ============================================

CREATE TABLE IF NOT EXISTS public.expense_2022 (
    -- Primary Key: Auto-incrementing integer
    expense_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Month: Full name (e.g., "January", "February")
    month             VARCHAR(20) NOT NULL,

    -- Year: 4-digit year (always 2022 for this table)
    year              INTEGER NOT NULL DEFAULT 2022,

    -- Category Reference (denormalized for performance)
    category_id       INTEGER NOT NULL,
    category_name     VARCHAR(50) NOT NULL,
    category_icon     VARCHAR(10),

    -- Subcategory (from category table's sub_category field)
    sub_category      VARCHAR(100),
    subcategory_icon  VARCHAR(10),

    -- Amount: Expense amount in INR (₹)
    amount_inr        DECIMAL(12, 2) NOT NULL CHECK (amount_inr >= 0),

    -- Notes: Optional description/comments
    notes             TEXT,

    -- Soft Delete Flag: FALSE = active, TRUE = deleted
    is_delete         BOOLEAN NOT NULL DEFAULT FALSE,

    -- Audit Timestamps: Automatically managed
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Constraint: Ensure year is 2022
    CONSTRAINT chk_expense_2022_year CHECK (year = 2022)
);

-- Indexes for expense_2022
CREATE INDEX IF NOT EXISTS idx_expense_2022_year_month ON public.expense_2022 (year, month);
CREATE INDEX IF NOT EXISTS idx_expense_2022_category ON public.expense_2022 (category_name);
CREATE INDEX IF NOT EXISTS idx_expense_2022_is_delete ON public.expense_2022 (is_delete);

-- Trigger for auto-update timestamp
DROP TRIGGER IF EXISTS trg_expense_2022_updated_at ON public.expense_2022;
CREATE TRIGGER trg_expense_2022_updated_at
    BEFORE UPDATE ON public.expense_2022
    FOR EACH ROW
    EXECUTE FUNCTION public.set_expense_updated_at();

-- Disable RLS
ALTER TABLE public.expense_2022 DISABLE ROW LEVEL SECURITY;


-- ============================================
-- EXPENSE TABLE 2023
-- ============================================

CREATE TABLE IF NOT EXISTS public.expense_2023 (
    -- Primary Key: Auto-incrementing integer
    expense_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Month: Full name (e.g., "January", "February")
    month             VARCHAR(20) NOT NULL,

    -- Year: 4-digit year (always 2023 for this table)
    year              INTEGER NOT NULL DEFAULT 2023,

    -- Category Reference (denormalized for performance)
    category_id       INTEGER NOT NULL,
    category_name     VARCHAR(50) NOT NULL,
    category_icon     VARCHAR(10),

    -- Subcategory (from category table's sub_category field)
    sub_category      VARCHAR(100),
    subcategory_icon  VARCHAR(10),

    -- Amount: Expense amount in INR (₹)
    amount_inr        DECIMAL(12, 2) NOT NULL CHECK (amount_inr >= 0),

    -- Notes: Optional description/comments
    notes             TEXT,

    -- Soft Delete Flag: FALSE = active, TRUE = deleted
    is_delete         BOOLEAN NOT NULL DEFAULT FALSE,

    -- Audit Timestamps: Automatically managed
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Constraint: Ensure year is 2023
    CONSTRAINT chk_expense_2023_year CHECK (year = 2023)
);

-- Indexes for expense_2023
CREATE INDEX IF NOT EXISTS idx_expense_2023_year_month ON public.expense_2023 (year, month);
CREATE INDEX IF NOT EXISTS idx_expense_2023_category ON public.expense_2023 (category_name);
CREATE INDEX IF NOT EXISTS idx_expense_2023_is_delete ON public.expense_2023 (is_delete);

-- Trigger for auto-update timestamp
DROP TRIGGER IF EXISTS trg_expense_2023_updated_at ON public.expense_2023;
CREATE TRIGGER trg_expense_2023_updated_at
    BEFORE UPDATE ON public.expense_2023
    FOR EACH ROW
    EXECUTE FUNCTION public.set_expense_updated_at();

-- Disable RLS
ALTER TABLE public.expense_2023 DISABLE ROW LEVEL SECURITY;


-- ============================================
-- EXPENSE TABLE 2024
-- ============================================

CREATE TABLE IF NOT EXISTS public.expense_2024 (
    -- Primary Key: Auto-incrementing integer
    expense_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Month: Full name (e.g., "January", "February")
    month             VARCHAR(20) NOT NULL,

    -- Year: 4-digit year (always 2024 for this table)
    year              INTEGER NOT NULL DEFAULT 2024,

    -- Category Reference (denormalized for performance)
    category_id       INTEGER NOT NULL,
    category_name     VARCHAR(50) NOT NULL,
    category_icon     VARCHAR(10),

    -- Subcategory (from category table's sub_category field)
    sub_category      VARCHAR(100),
    subcategory_icon  VARCHAR(10),

    -- Amount: Expense amount in INR (₹)
    amount_inr        DECIMAL(12, 2) NOT NULL CHECK (amount_inr >= 0),

    -- Notes: Optional description/comments
    notes             TEXT,

    -- Soft Delete Flag: FALSE = active, TRUE = deleted
    is_delete         BOOLEAN NOT NULL DEFAULT FALSE,

    -- Audit Timestamps: Automatically managed
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Constraint: Ensure year is 2024
    CONSTRAINT chk_expense_2024_year CHECK (year = 2024)
);

-- Indexes for expense_2024
CREATE INDEX IF NOT EXISTS idx_expense_2024_year_month ON public.expense_2024 (year, month);
CREATE INDEX IF NOT EXISTS idx_expense_2024_category ON public.expense_2024 (category_name);
CREATE INDEX IF NOT EXISTS idx_expense_2024_is_delete ON public.expense_2024 (is_delete);

-- Trigger for auto-update timestamp
DROP TRIGGER IF EXISTS trg_expense_2024_updated_at ON public.expense_2024;
CREATE TRIGGER trg_expense_2024_updated_at
    BEFORE UPDATE ON public.expense_2024
    FOR EACH ROW
    EXECUTE FUNCTION public.set_expense_updated_at();

-- Disable RLS
ALTER TABLE public.expense_2024 DISABLE ROW LEVEL SECURITY;


-- ============================================
-- EXPENSE TABLE 2025
-- ============================================

CREATE TABLE IF NOT EXISTS public.expense_2025 (
    -- Primary Key: Auto-incrementing integer
    expense_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Month: Full name (e.g., "January", "February")
    month             VARCHAR(20) NOT NULL,

    -- Year: 4-digit year (always 2025 for this table)
    year              INTEGER NOT NULL DEFAULT 2025,

    -- Category Reference (denormalized for performance)
    category_id       INTEGER NOT NULL,
    category_name     VARCHAR(50) NOT NULL,
    category_icon     VARCHAR(10),

    -- Subcategory (from category table's sub_category field)
    sub_category      VARCHAR(100),
    subcategory_icon  VARCHAR(10),

    -- Amount: Expense amount in INR (₹)
    amount_inr        DECIMAL(12, 2) NOT NULL CHECK (amount_inr >= 0),

    -- Notes: Optional description/comments
    notes             TEXT,

    -- Soft Delete Flag: FALSE = active, TRUE = deleted
    is_delete         BOOLEAN NOT NULL DEFAULT FALSE,

    -- Audit Timestamps: Automatically managed
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Constraint: Ensure year is 2025
    CONSTRAINT chk_expense_2025_year CHECK (year = 2025)
);

-- Indexes for expense_2025
CREATE INDEX IF NOT EXISTS idx_expense_2025_year_month ON public.expense_2025 (year, month);
CREATE INDEX IF NOT EXISTS idx_expense_2025_category ON public.expense_2025 (category_name);
CREATE INDEX IF NOT EXISTS idx_expense_2025_is_delete ON public.expense_2025 (is_delete);

-- Trigger for auto-update timestamp
DROP TRIGGER IF EXISTS trg_expense_2025_updated_at ON public.expense_2025;
CREATE TRIGGER trg_expense_2025_updated_at
    BEFORE UPDATE ON public.expense_2025
    FOR EACH ROW
    EXECUTE FUNCTION public.set_expense_updated_at();

-- Disable RLS
ALTER TABLE public.expense_2025 DISABLE ROW LEVEL SECURITY;


-- ============================================
-- VERIFICATION QUERIES
-- ============================================

-- Check all expense tables exist
SELECT table_name 
FROM information_schema.tables 
WHERE table_schema = 'public' 
  AND table_name LIKE 'expense_%'
ORDER BY table_name;

-- Check row counts
SELECT 'expense_2021' as table_name, COUNT(*) as row_count FROM public.expense_2021
UNION ALL
SELECT 'expense_2022', COUNT(*) FROM public.expense_2022
UNION ALL
SELECT 'expense_2023', COUNT(*) FROM public.expense_2023
UNION ALL
SELECT 'expense_2024', COUNT(*) FROM public.expense_2024
UNION ALL
SELECT 'expense_2025', COUNT(*) FROM public.expense_2025
ORDER BY table_name;
