-- ============================================
-- 1) CREATE TABLE
-- ============================================

CREATE TABLE IF NOT EXISTS public.tax (
    -- Primary Key: Auto-incrementing integer
    tax_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Year: Calendar year (e.g., 2021, 2022, 2023, 2024, 2025, 2026)
    year           INTEGER NOT NULL CHECK (year BETWEEN 2021 AND 2030),
    
    -- Month: Month number (1-12)
    month          INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
    
    -- Tax Paid: Amount of tax paid in INR (₹)
    -- Using DECIMAL for precise currency calculations
    tax_paid       DECIMAL(12, 2) NOT NULL DEFAULT 0 CHECK (tax_paid >= 0),
    
    -- Taxable Income: Income for this month (optional)
    taxable_income DECIMAL(12, 2) DEFAULT 0 CHECK (taxable_income >= 0),
    
    -- Status: Payment status
    status         VARCHAR(20) NOT NULL DEFAULT 'paid' CHECK (status IN ('paid', 'pending', 'overdue')),
    
    -- Payment Date: When tax was paid
    payment_date   DATE,
    
    -- Payment Mode: How tax was paid
    payment_mode   VARCHAR(50) DEFAULT 'Online',
    
    -- Notes: Optional description/comments
    notes          TEXT,
    
    -- Audit Timestamps: Automatically managed
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_deleted     BOOLEAN NOT NULL DEFAULT FALSE,
    
    -- Unique constraint: Prevent duplicate entries for same month/year
    CONSTRAINT ux_tax_year_month UNIQUE (year, month)
);

-- ============================================
-- 2) CREATE INDEXES
-- ============================================

-- Index on year for fast year-based filtering
CREATE INDEX IF NOT EXISTS idx_tax_year ON public.tax(year);

-- Index on month for monthly reports
CREATE INDEX IF NOT EXISTS idx_tax_month ON public.tax(month);

-- Composite index on year and month for efficient queries
CREATE INDEX IF NOT EXISTS idx_tax_year_month ON public.tax(year, month);

-- Index on status for filtering
CREATE INDEX IF NOT EXISTS idx_tax_status ON public.tax(status);

-- Index on is_deleted for active records filtering
CREATE INDEX IF NOT EXISTS idx_tax_active ON public.tax(is_deleted);

-- ============================================
-- 3) CREATE TRIGGER FOR UPDATED_AT
-- ============================================

CREATE OR REPLACE FUNCTION update_tax_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_tax_updated_at
BEFORE UPDATE ON public.tax
FOR EACH ROW
EXECUTE FUNCTION update_tax_timestamp();


COMMENT ON TABLE public.tax IS 'Stores monthly tax payment entries for personal finance tracking';
COMMENT ON COLUMN public.tax.tax_id IS 'Primary key - auto-incrementing';
COMMENT ON COLUMN public.tax.year IS 'Calendar year (2021-2030)';
COMMENT ON COLUMN public.tax.month IS 'Month number (1-12)';
COMMENT ON COLUMN public.tax.tax_paid IS 'Amount of tax paid in INR';
COMMENT ON COLUMN public.tax.taxable_income IS 'Taxable income for the month';
COMMENT ON COLUMN public.tax.status IS 'Payment status: paid, pending, overdue';
COMMENT ON COLUMN public.tax.payment_date IS 'Date when tax was paid';
COMMENT ON COLUMN public.tax.payment_mode IS 'Payment method';
COMMENT ON COLUMN public.tax.notes IS 'Additional notes or comments';
COMMENT ON COLUMN public.tax.is_deleted IS 'Soft delete flag';