-- ============================================
-- Bug Fixes V8: Add Icon Columns to Category Table
-- ============================================
-- Description: Adds category_icon and subcategory_icon columns 
--              to store icons permanently in database
-- Date: March 15, 2026
-- Author: Cashflow Portal Team
-- ============================================

-- Add category_icon column
ALTER TABLE category 
ADD COLUMN IF NOT EXISTS category_icon VARCHAR(10);

-- Add subcategory_icon column
ALTER TABLE category 
ADD COLUMN IF NOT EXISTS subcategory_icon VARCHAR(10);

-- Add comments to document the columns
COMMENT ON COLUMN category.category_icon IS 'Stores the emoji icon for the category (e.g., 🍕, 🚗, 🎬)';
COMMENT ON COLUMN category.subcategory_icon IS 'Stores the emoji icon for the subcategory (e.g., 🍔, 🚕, 🎭)';

-- Create indexes for better performance when updating icons by name
CREATE INDEX IF NOT EXISTS idx_category_name ON category(category_name);
CREATE INDEX IF NOT EXISTS idx_sub_category ON category(sub_category);

-- Verify the changes
SELECT 
    column_name, 
    data_type, 
    character_maximum_length,
    is_nullable,
    column_default
FROM information_schema.columns 
WHERE table_name = 'category' 
  AND column_name IN ('category_icon', 'subcategory_icon')
ORDER BY ordinal_position;

-- Show current table structure
\d category;

-- ============================================
-- MIGRATION NOTES
-- ============================================
-- 1. Existing categories will have NULL icons initially
-- 2. Icons will be auto-generated by IconMapper.getIcon() in the frontend
-- 3. When users edit categories, they can select custom icons which will be saved
-- 4. The application supports 120+ emoji icons organized by category
-- 5. Icons are optional fields (nullable)
-- 
-- Icon Priority Logic (in getCategoryIcon method):
-- 1. Database icon (category_icon or subcategory_icon)
-- 2. localStorage custom selection (legacy support)
-- 3. Auto-generated icon from IconMapper based on category name
-- ============================================

-- ============================================
-- ROLLBACK SCRIPT (if needed)
-- ============================================
-- Uncomment to remove the columns:
-- ALTER TABLE category DROP COLUMN IF EXISTS category_icon;
-- ALTER TABLE category DROP COLUMN IF EXISTS subcategory_icon;
-- ============================================

-- Success message
SELECT '✅ Icon columns added successfully to category table!' AS status;
