-- ============================================
-- File: 001_category.sql
-- Purpose: Category table schema definition
-- Author: Copilot AI Assistant
-- Date: 2026-03-13
-- Version: 1.0
-- Dependencies: dbo schema
-- ============================================

-- Description:
-- This table stores expense/income categories for the cashflow portal.
-- Each category has a unique name (case-insensitive) and an active status flag.
-- Soft delete is implemented via is_active flag.

-- ============================================
-- 1) CREATE SCHEMA (if using custom schema)
-- ============================================

-- Note: "dbo" is typically SQL Server convention. 
-- In PostgreSQL, "public" is default.
-- Create only if you specifically want "dbo" schema.

CREATE SCHEMA IF NOT EXISTS dbo;


-- ============================================
-- 2) CREATE TABLE
-- ============================================

CREATE TABLE IF NOT EXISTS dbo.category (
    -- Primary Key: Auto-incrementing integer
    category_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Category Name: Required, max 50 characters
    category_name  VARCHAR(50) NOT NULL,
    
    -- Soft Delete Flag: TRUE = active, FALSE = deleted
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    
    -- Audit Timestamps: Automatically managed
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================
-- 3) CREATE UNIQUE INDEX (Case-Insensitive)
-- ============================================

-- Purpose: Prevent duplicate category names like 'Fuel' and 'fuel'
-- Uses LOWER() function to enforce case-insensitive uniqueness

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes 
    WHERE schemaname = 'dbo' 
      AND indexname = 'ux_category_name_ci'
  ) THEN
    CREATE UNIQUE INDEX ux_category_name_ci
      ON dbo.category (LOWER(category_name));
  END IF;
END$$;


-- ============================================
-- 4) CREATE TRIGGER FUNCTION (Auto-update timestamp)
-- ============================================

-- Purpose: Automatically set updated_at to NOW() on every UPDATE
-- This ensures audit trail is maintained without manual updates

CREATE OR REPLACE FUNCTION dbo.set_category_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ============================================
-- 5) CREATE TRIGGER
-- ============================================

-- Purpose: Fire trigger function before UPDATE operations
-- Ensures updated_at is always current

DROP TRIGGER IF EXISTS trg_category_updated_at ON dbo.category;

CREATE TRIGGER trg_category_updated_at
BEFORE UPDATE ON dbo.category
FOR EACH ROW
EXECUTE FUNCTION dbo.set_category_updated_at();


-- ============================================
-- VERIFICATION QUERIES
-- ============================================

-- Check table structure
-- SELECT * FROM information_schema.columns WHERE table_schema = 'dbo' AND table_name = 'category';

-- Check indexes
-- SELECT * FROM pg_indexes WHERE schemaname = 'dbo' AND tablename = 'category';

-- Check triggers
-- SELECT * FROM pg_trigger WHERE tgrelid = 'dbo.category'::regclass;


-- ============================================
-- ROLLBACK (How to undo)
-- ============================================

-- WARNING: This will delete all data!
-- DROP TRIGGER IF EXISTS trg_category_updated_at ON dbo.category;
-- DROP FUNCTION IF EXISTS dbo.set_category_updated_at();
-- DROP TABLE IF EXISTS dbo.category CASCADE;
-- DROP SCHEMA IF EXISTS dbo CASCADE;


-- ============================================
-- NOTES
-- ============================================

-- 1. Auto-increment starts at 1 by default
-- 2. TIMESTAMPTZ stores timezone-aware timestamps (recommended for global apps)
-- 3. Unique index on LOWER(category_name) prevents case duplicates
-- 4. Trigger automatically maintains updated_at - no manual updates needed
-- 5. Soft delete via is_active - data never truly deleted for audit trail
-- 6. Consider adding user_id column if multi-user support needed

-- ============================================
-- RELATED FILES
-- ============================================

-- Angular Service: src/app/services/category.service.ts
-- Angular Component: src/app/component/category/category.page.ts
-- Seed Data: sql/seeds/category_seed.sql
-- Common Queries: sql/queries/category_queries.sql
