-- ============================================
-- File: 007_debts.sql
-- Purpose: Create debts table for managing loans and debts to pay/receive
-- Author: Copilot AI Assistant
-- Date: 2026-04-03
-- Version: 1.0
-- ============================================

-- Description:
-- This table manages both debts (money owed by user) and receivables (money owed to user)
-- Supports tracking of loan details, EMI, status, and payment history

-- ============================================
-- DEBTS TABLE
-- ============================================

CREATE TABLE IF NOT EXISTS public.debts (
    -- Primary Key: Auto-incrementing integer
    debt_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Debt Type: 'debt' (I owe) or 'receivable' (they owe me)
    debt_type         VARCHAR(20) NOT NULL CHECK (debt_type IN ('debt', 'receivable')),

    -- Loan/Debt Details
    loan_name         VARCHAR(100) NOT NULL,
    bank_or_person    VARCHAR(100) NOT NULL,  -- Bank name or person name
    principal_amount  DECIMAL(12, 2) NOT NULL CHECK (principal_amount >= 0),
    interest_rate     DECIMAL(5, 2),  -- Optional interest rate (percentage)
    
    -- EMI Details
    emi_amount        DECIMAL(12, 2) CHECK (emi_amount >= 0),
    emi_start_date    DATE,
    emi_end_date      DATE,
    
    -- Current Status
    outstanding_amount DECIMAL(12, 2) NOT NULL CHECK (outstanding_amount >= 0),
    amount_paid       DECIMAL(12, 2) NOT NULL DEFAULT 0 CHECK (amount_paid >= 0),
    
    -- Status: 'open' or 'closed'
    status            VARCHAR(20) NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
    
    -- Additional Info
    notes             TEXT,
    
    -- Soft Delete Flag
    is_delete         BOOLEAN NOT NULL DEFAULT FALSE,
    
    -- Audit Timestamps
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================
-- INDEXES
-- ============================================

CREATE INDEX IF NOT EXISTS idx_debts_type ON public.debts (debt_type);
CREATE INDEX IF NOT EXISTS idx_debts_status ON public.debts (status);
CREATE INDEX IF NOT EXISTS idx_debts_is_delete ON public.debts (is_delete);
CREATE INDEX IF NOT EXISTS idx_debts_bank_person ON public.debts (bank_or_person);

-- ============================================
-- TRIGGER FOR AUTO-UPDATE TIMESTAMP
-- ============================================

-- Create trigger function if not exists (reuse from expense table)
CREATE OR REPLACE FUNCTION public.set_debts_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger
DROP TRIGGER IF EXISTS trg_debts_updated_at ON public.debts;
CREATE TRIGGER trg_debts_updated_at
    BEFORE UPDATE ON public.debts
    FOR EACH ROW
    EXECUTE FUNCTION public.set_debts_updated_at();

-- ============================================
-- DISABLE RLS (for Supabase free tier)
-- ============================================

ALTER TABLE public.debts DISABLE ROW LEVEL SECURITY;

-- ============================================
-- SEED DATA (Initial debts based on your list)
-- ============================================

INSERT INTO public.debts (
    debt_type,
    loan_name,
    bank_or_person,
    principal_amount,
    interest_rate,
    emi_amount,
    outstanding_amount,
    amount_paid,
    status,
    notes
) VALUES
-- Closed Debts
(
    'debt',
    'BOB Education Loan',
    'Bank of Baroda',
    500000.00,
    8.5,
    15000.00,
    0.00,
    500000.00,
    'closed',
    'Education loan for higher studies - Fully paid'
),
(
    'debt',
    'SBI Gold Loan',
    'State Bank of India',
    150000.00,
    10.5,
    0.00,
    0.00,
    150000.00,
    'closed',
    'Gold loan - Fully repaid'
),
(
    'debt',
    'HDFC Personal Loan',
    'HDFC Bank',
    300000.00,
    12.0,
    10000.00,
    0.00,
    300000.00,
    'closed',
    'Personal loan - Closed'
),
-- Open Debt
(
    'debt',
    'HDFC Personal Loan - Top Up',
    'HDFC Bank',
    200000.00,
    11.5,
    8500.00,
    125000.00,
    75000.00,
    'open',
    'Personal loan top-up - Currently paying EMI'
);

-- ============================================
-- VERIFICATION QUERIES
-- ============================================

-- Check table exists
SELECT table_name 
FROM information_schema.tables 
WHERE table_schema = 'public' 
  AND table_name = 'debts';

-- Check all debts
SELECT 
    debt_id,
    debt_type,
    loan_name,
    bank_or_person,
    principal_amount,
    outstanding_amount,
    status,
    created_at
FROM public.debts
WHERE is_delete = false
ORDER BY status ASC, created_at DESC;

-- Summary by status
SELECT 
    status,
    COUNT(*) as count,
    SUM(principal_amount) as total_principal,
    SUM(outstanding_amount) as total_outstanding,
    SUM(amount_paid) as total_paid
FROM public.debts
WHERE is_delete = false
GROUP BY status
ORDER BY status;

-- Summary by type
SELECT 
    debt_type,
    status,
    COUNT(*) as count,
    SUM(outstanding_amount) as total_outstanding
FROM public.debts
WHERE is_delete = false
GROUP BY debt_type, status
ORDER BY debt_type, status;
