-- ============================================
-- File: 007_lifeline.sql
-- Purpose: Lifeline table schema definition
-- Author: Copilot AI Assistant
-- Date: 2026-05-16
-- Version: 1.0
-- Dependencies: public schema
-- ============================================

-- Description:
-- This table stores lifeline entries for tracking important financial events/milestones.
-- Includes date, INR amount, and optional notes for each entry.

-- ============================================
-- 1) CREATE TABLE
-- ============================================

CREATE TABLE IF NOT EXISTS public.lifeline (
    -- Primary Key: Auto-incrementing integer
    lifeline_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Date: When this lifeline entry occurred
    entry_date     DATE NOT NULL,
    
    -- Amount: Amount in INR (₹)
    -- Using DECIMAL for precise currency calculations
    amount_inr     DECIMAL(12, 2) NOT NULL CHECK (amount_inr >= 0),
    
    -- Notes: Description/comments for this entry
    notes          TEXT,
    
    -- Soft Delete Flag
    is_delete      BOOLEAN NOT NULL DEFAULT FALSE,
    
    -- Audit Timestamps: Automatically managed
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================
-- 2) INDEXES
-- ============================================

-- Index for faster date-based queries
CREATE INDEX IF NOT EXISTS idx_lifeline_entry_date 
ON public.lifeline(entry_date DESC);

-- Index for non-deleted records
CREATE INDEX IF NOT EXISTS idx_lifeline_active 
ON public.lifeline(is_delete) 
WHERE is_delete = FALSE;

-- ============================================
-- 3) TRIGGER FOR UPDATED_AT
-- ============================================

-- Function to auto-update the updated_at timestamp
CREATE OR REPLACE FUNCTION public.update_lifeline_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to call the function before each update
DROP TRIGGER IF EXISTS trg_lifeline_updated_at ON public.lifeline;
CREATE TRIGGER trg_lifeline_updated_at
    BEFORE UPDATE ON public.lifeline
    FOR EACH ROW
    EXECUTE FUNCTION public.update_lifeline_timestamp();

-- ============================================
-- 4) COMMENTS
-- ============================================

COMMENT ON TABLE public.lifeline IS 'Stores lifeline entries for tracking important financial events';
COMMENT ON COLUMN public.lifeline.lifeline_id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN public.lifeline.entry_date IS 'Date of the lifeline entry';
COMMENT ON COLUMN public.lifeline.amount_inr IS 'Amount in Indian Rupees (INR)';
COMMENT ON COLUMN public.lifeline.notes IS 'Optional notes/description for this entry';
COMMENT ON COLUMN public.lifeline.is_delete IS 'Soft delete flag (TRUE = deleted)';
COMMENT ON COLUMN public.lifeline.created_at IS 'Record creation timestamp';
COMMENT ON COLUMN public.lifeline.updated_at IS 'Record last update timestamp';

-- ============================================
-- 5) ROW LEVEL SECURITY (Optional)
-- ============================================

-- Enable RLS on the table
ALTER TABLE public.lifeline ENABLE ROW LEVEL SECURITY;

-- Policy to allow all operations for authenticated users
CREATE POLICY lifeline_policy ON public.lifeline
    FOR ALL
    USING (TRUE)
    WITH CHECK (TRUE);

-- ============================================
-- 6) SAMPLE QUERIES
-- ============================================

-- Get all active lifeline entries (sorted by date descending)
-- SELECT * FROM public.lifeline WHERE is_delete = FALSE ORDER BY entry_date DESC;

-- Get total amount of all active entries
-- SELECT SUM(amount_inr) AS total_amount FROM public.lifeline WHERE is_delete = FALSE;

-- Insert a new entry
-- INSERT INTO public.lifeline (entry_date, amount_inr, notes)
-- VALUES ('2026-05-16', 50000.00, 'Emergency fund milestone');

-- Soft delete an entry
-- UPDATE public.lifeline SET is_delete = TRUE WHERE lifeline_id = 1;

-- Update an entry
-- UPDATE public.lifeline SET amount_inr = 75000.00, notes = 'Updated note' WHERE lifeline_id = 1;
