-- ============================================
-- File: 009_payslip.sql
-- Purpose: Monthly payslip PDF upload metadata table schema definition
-- Author: Copilot AI Assistant
-- Date: 2026-09-30
-- Version: 1.1
-- Dependencies: public schema, Supabase Storage bucket "payslips"
-- ============================================

-- Description:
-- Stores metadata for one uploaded payslip PDF per month/year.
-- The actual PDF file bytes are stored in Supabase Storage (bucket: "payslips");
-- this table only stores the storage path + display metadata.

-- ============================================
-- 0) STORAGE BUCKET (run once via Supabase Dashboard or SQL editor)
-- ============================================
-- Bucket is PUBLIC because the free Supabase tier does not support
-- signed URLs on private buckets the same way (and to keep things simple).
-- Anyone with the file URL can view it, so avoid storing highly sensitive
-- documents here, or restrict access at the app layer (auth-gated routes).

insert into storage.buckets (id, name, public)
values ('payslips', 'payslips', true)
on conflict (id) do update set public = true;

-- Making a bucket "public" only allows public READ of files; it does NOT
-- grant permission to upload/delete. storage.objects has its own RLS
-- (enabled by default in Supabase) and needs explicit policies below.
-- This app authenticates via a custom OTP flow, not Supabase Auth, so all
-- Supabase requests run as the "anon" role — policies must allow "anon".

DROP POLICY IF EXISTS payslips_read ON storage.objects;
CREATE POLICY payslips_read ON storage.objects
    FOR SELECT
    TO anon, authenticated
    USING (bucket_id = 'payslips');

DROP POLICY IF EXISTS payslips_insert ON storage.objects;
CREATE POLICY payslips_insert ON storage.objects
    FOR INSERT
    TO anon, authenticated
    WITH CHECK (bucket_id = 'payslips');

DROP POLICY IF EXISTS payslips_update ON storage.objects;
CREATE POLICY payslips_update ON storage.objects
    FOR UPDATE
    TO anon, authenticated
    USING (bucket_id = 'payslips')
    WITH CHECK (bucket_id = 'payslips');

DROP POLICY IF EXISTS payslips_delete ON storage.objects;
CREATE POLICY payslips_delete ON storage.objects
    FOR DELETE
    TO anon, authenticated
    USING (bucket_id = 'payslips');

-- ============================================
-- 1) CREATE TABLE
-- ============================================

CREATE TABLE IF NOT EXISTS public.payslip (
    -- Primary Key: Auto-incrementing integer
    payslip_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Month: Full name (e.g., "January", "February")
    month          VARCHAR(20) NOT NULL,

    -- Year: 4-digit year
    year           INTEGER NOT NULL,

    -- Original uploaded file name (for display/download)
    file_name      VARCHAR(255) NOT NULL,

    -- Path inside the "payslips" Storage bucket, e.g. "2026/August_2026_<timestamp>_<name>.pdf"
    file_path      TEXT NOT NULL,

    -- File size in bytes (informational, shown in UI)
    file_size      INTEGER,

    -- Notes: Optional description/comments
    notes          TEXT,

    -- Soft delete flag
    is_delete      BOOLEAN NOT NULL DEFAULT FALSE,

    -- Audit Timestamps: Automatically managed
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Prevent duplicate payslip for same month/year while active
    CONSTRAINT ux_payslip_month_year UNIQUE (month, year)
);

-- ============================================
-- 2) INDEXES
-- ============================================

CREATE INDEX IF NOT EXISTS idx_payslip_year
  ON public.payslip(year DESC);

CREATE INDEX IF NOT EXISTS idx_payslip_active
  ON public.payslip(is_delete)
  WHERE is_delete = FALSE;

-- ============================================
-- 3) TRIGGER FOR UPDATED_AT
-- ============================================

CREATE OR REPLACE FUNCTION public.update_payslip_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_payslip_updated_at ON public.payslip;
CREATE TRIGGER trg_payslip_updated_at
    BEFORE UPDATE ON public.payslip
    FOR EACH ROW
    EXECUTE FUNCTION public.update_payslip_timestamp();

-- ============================================
-- 4) COMMENTS
-- ============================================

COMMENT ON TABLE public.payslip IS 'Stores metadata for uploaded monthly payslip PDFs (file stored in Supabase Storage)';
COMMENT ON COLUMN public.payslip.payslip_id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN public.payslip.month IS 'Full month name, e.g. January';
COMMENT ON COLUMN public.payslip.year IS 'Calendar year';
COMMENT ON COLUMN public.payslip.file_name IS 'Original uploaded file name';
COMMENT ON COLUMN public.payslip.file_path IS 'Path inside the payslips Storage bucket';
COMMENT ON COLUMN public.payslip.file_size IS 'File size in bytes';
COMMENT ON COLUMN public.payslip.notes IS 'Optional notes/description for this entry';
COMMENT ON COLUMN public.payslip.is_delete IS 'Soft delete flag (TRUE = deleted)';
COMMENT ON COLUMN public.payslip.created_at IS 'Record creation timestamp';
COMMENT ON COLUMN public.payslip.updated_at IS 'Record last update timestamp';

-- ============================================
-- 5) ROW LEVEL SECURITY
-- ============================================

ALTER TABLE public.payslip ENABLE ROW LEVEL SECURITY;

-- Policy to allow all operations (single-user personal finance app, anon role via custom OTP auth)
DROP POLICY IF EXISTS payslip_policy ON public.payslip;
CREATE POLICY payslip_policy ON public.payslip
    FOR ALL
    TO anon, authenticated
    USING (TRUE)
    WITH CHECK (TRUE);

